name: knulli-build

services:
  knulli:
    image: bremedios/knulli-build:latest
    volumes:
      - type: volume
        source: knulli_build-rk3128
        target: /build
      - type: volume
        source: knulli_toolchain-rk3128
        target: /home/ubuntu/toolchains
      - type: volume
        source: knulli_buildroot_cache-rk3128
        target: /home/ubuntu/.buildroot-ccache
      - type: bind
        source: ./keys.txt
        target: /home/ubuntu/keys.txt
      - type: bind
        source: ./output
        target: /home/ubuntu/output
    entrypoint: /home/ubuntu/start_rk3128.sh
volumes:
  knulli_build-rk3128:
    name: knulli_build-rk3128
  knulli_toolchain-rk3128:
    name: knulli_toolchain-rk3128
  knulli_buildroot_cache-rk3128:
    name: knulli_buildroot_cache-rk3128
