name: knulli-build

services:
  knulli:
    image: bremedios/knulli-build:latest
    volumes:
      - type: volume
        source: knulli_build-a133
        target: /build
      - type: volume
        source: knulli_toolchain-a133
        target: /home/ubuntu/toolchains
      - type: volume
        source: knulli_buildroot_cache-a133
        target: /home/ubuntu/.buildroot-ccache
      - type: bind
        source: ./keys.txt
        target: /home/ubuntu/keys.txt
      - type: bind
        source: ./output
        target: /home/ubuntu/output
    entrypoint: /home/ubuntu/start_a133.sh
volumes:
  knulli_build-a133:
    name: knulli_build-a133
  knulli_toolchain-a133:
    name: knulli_toolchain-a133
  knulli_buildroot_cache-a133:
    name: knulli_buildroot_cache-a133
