name: knulli-build

services:
  knulli:
    image: bremedios/knulli-build:latest
    volumes:
      - type: volume
        source: knulli_build-h700
        target: /build
      - type: volume
        source: knulli_toolchain-h700
        target: /home/ubuntu/toolchains
      - type: volume
        source: knulli_buildroot_cache-h700
        target: /home/ubuntu/.buildroot-ccache
      - type: bind
        source: ./keys.txt
        target: /home/ubuntu/keys.txt
      - type: bind
        source: ./output
        target: /home/ubuntu/output
    entrypoint: /home/ubuntu/start_h700.sh
volumes:
  knulli_build-h700:
    name: knulli_build-h700
  knulli_toolchain-h700:
    name: knulli_toolchain-h700
  knulli_buildroot_cache-h700:
    name: knulli_buildroot_cache-h700
