name: knulli-build

services:
  knulli:
    image: bremedios/knulli-build:latest
    volumes:
      - type: volume
        source: knulli_build-sm8250
        target: /home/developer/build
      - type: volume
        source: knulli_toolchain-sm8250
        target: /home/developer/toolchains
      - type: volume
        source: knulli_buildroot_cache-sm8250
        target: /home/developer/.buildroot-ccache
      - type: bind
        source: ./output
        target: /home/developer/output
    entrypoint: /home/developer/start_sm8250.sh
volumes:
  knulli_build-sm8250:
    name: knulli_build-sm8250
  knulli_toolchain-sm8250:
    name: knulli_toolchain-sm8250
  knulli_buildroot_cache-sm8250:
    name: knulli_buildroot_cache-sm8250
