name: knulli-build

services:
  knulli:
    image: bremedios/knulli-build:latest
    volumes:
      - type: volume
        source: knulli_build-rk3566
        target: /home/developer/build
      - type: volume
        source: knulli_toolchain-rk3566
        target: /home/developer/toolchains
      - type: volume
        source: knulli_buildroot_cache-rk3566
        target: /home/developer/.buildroot-ccache
      - type: bind
        source: ./keys.txt
        target: /home/developer/keys.txt
      - type: bind
        source: ./output
        target: /home/developer/output
    entrypoint: /home/developer/start_rk3566.sh
volumes:
  knulli_build-rk3566:
    name: knulli_build-rk3566
  knulli_toolchain-rk3566:
    name: knulli_toolchain-rk3566
  knulli_buildroot_cache-rk3566:
    name: knulli_buildroot_cache-rk3566
