name: knulli-build

services:
  knulli:
    image: bremedios/knulli-build:latest
    volumes:
      - type: volume
        source: knulli_build-atm7039
        target: /build
      - type: volume
        source: knulli_toolchain-atm7039
        target: /home/ubuntu/toolchains
      - type: volume
        source: knulli_buildroot_cache-atm7039
        target: /home/ubuntu/.buildroot-ccache
      - type: bind
        source: ./keys.txt
        target: /home/ubuntu/keys.txt
      - type: bind
        source: ./output
        target: /home/ubuntu/output
    entrypoint: /home/ubuntu/start_atm7039.sh
volumes:
  knulli_build-atm7039:
    name: knulli_build-atm7039
  knulli_toolchain-atm7039:
    name: knulli_toolchain-atm7039
  knulli_buildroot_cache-atm7039:
    name: knulli_buildroot_cache-atm7039
