name: knulli-build

services:
  knulli:
    image: bremedios/knulli-build:latest
    volumes:
      - type: volume
        source: knulli_build-sm8250
        target: /build
      - type: volume
        source: knulli_toolchain-sm8250
        target: /home/ubuntu/toolchains
      - type: volume
        source: knulli_buildroot_cache-sm8250
        target: /home/ubuntu/.buildroot-ccache
      - type: bind
        source: ./keys.txt
        target: /home/ubuntu/keys.txt
      - type: bind
        source: ./output
        target: /home/ubuntu/output
    entrypoint: /home/ubuntu/start_sm8250.sh
volumes:
  knulli_build-sm8250:
    name: knulli_build-sm8250
  knulli_toolchain-sm8250:
    name: knulli_toolchain-sm8250
  knulli_buildroot_cache-sm8250:
    name: knulli_buildroot_cache-sm8250
